"C:\Program Files\Python39\python.exe" "C:/Python/Модуль 5. Python в веб-разработке/hw/my-hw-py-web/hw_5_8_aiohttp/site_aiohttp/main.py"
======== Running on http://0.0.0.0:8000 ========
(Press CTRL+C to quit)
<Request GET /ads/1 >
Error handling request
Traceback (most recent call last):
  File "C:\Users\TVP\AppData\Roaming\Python\Python39\site-packages\aiohttp\web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "C:\Users\TVP\AppData\Roaming\Python\Python39\site-packages\aiohttp\web_app.py", line 499, in _handle
    resp = await handler(request)
  File "C:\Python\Модуль 5. Python в веб-разработке\hw\my-hw-py-web\hw_5_8_aiohttp\site_aiohttp\main.py", line 37, in get_ad
    ad_id = self.request.match_info['ad_id']
AttributeError: 'Request' object has no attribute 'request'
<Request GET /ads/1 >
Error handling request
Traceback (most recent call last):
  File "C:\Users\TVP\AppData\Roaming\Python\Python39\site-packages\aiohttp\web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "C:\Users\TVP\AppData\Roaming\Python\Python39\site-packages\aiohttp\web_app.py", line 499, in _handle
    resp = await handler(request)
  File "C:\Python\Модуль 5. Python в веб-разработке\hw\my-hw-py-web\hw_5_8_aiohttp\site_aiohttp\main.py", line 37, in get_ad
    ad_id = self.request.match_info['ad_id']
AttributeError: 'Request' object has no attribute 'request'